### ISSUE TITLE
Pass-through more generic input attributes

### ISSUE THREAD

**Issue by denisnd** [buttercup/react-formatted-input#10]
It will be nice if `required` and `autoComplete` attributes are also passed through by `<FormattedInput/>`

**Comment by ryandagg** [comment]
Not passing through `id` makes this library unusable. There is a lot of browser functionality built into `<label>` when using `htmlFor` that is lost without passing `id` through.

**Comment by ryandagg** [comment]
I just created a PR to pass through all the things!
https://github.com/buttercup/react-formatted-input/pull/14

**Comment by perry-mitchell** [comment]
Hey thanks! I’ll try to get everything looked at and merged tomorrow.. or @sallar might be able to take a look.

**Comment by sallar** [comment]
I can check this today!
