### ISSUE TITLE
Formate date or time use regexp

### ISSUE THREAD

**Issue by SPavelV** [buttercup/react-formatted-input#15]
How to implement formatting input use regex?
For time: `^(0[0-9]|1[0-9]|2[0-3]|[0-9]):[0-5][0-9]$`
And date:` ^(((0[1-9]|[12]\d|3[01])\.(0[13578]|1[02])\.((19|[2-9]\d)\d{2}))|((0[1-9]|[12]\d|30)\.(0[13456789]|1[012])\.((19|[2-9]\d)\d{2}))|((0[1-9]|1\d|2[0-8])\.02\.((19|[2-9]\d)\d{2}))|(29\.02\.((1[6-9]|[2-9]\d)(0[48]|[2468][048]|[13579][26])|((16|[2468][048]|[3579][26])00))))$`

**Comment by perry-mitchell** [comment]
Hi! Currently this input works on a character by character validation approach as seen in the docs. There’s no way to map your expressions to that, as I can see there are several optional character ranges of different lengths. This library needs to know, position by position, what can go there. It wouldn’t be possible to add formatting characters in the middle of values without having this.

**Comment by perry-mitchell** [comment]
I’m afraid your expressions are complicated enough that it might be worthwhile writing your own components for them, wrapping an input element. As such I’m afraid it’s out of the scope of this library for now..
