### ISSUE TITLE
Support ref or focus() method

### ISSUE THREAD

**Issue by bolekro** [buttercup/react-formatted-input#18]
Trying to trigger focus() on the underlying input, however the FormattedInput does not expose it, neither does it pass a ref to the input do to it directly.

**Comment by pogo19** [comment]
ref support would be teriffic as I want to use it together with react-hook-form ;) For example Material-UI has a prop `inputRef` and its value is then passed to `ref` of the React `input`.

Anyway, great and yet simple formatted input. Thanks to authors for that.

**Comment by lbialy** [comment]
@pogo19 just use `<Controller />` if you want this to work with react-hook-form ;)

**Comment by pogo19** [comment]
> @pogo19 just use `<Controller />` if you want this to work with react-hook-form ;)

Yes, that is exactly what I did in the end ;)

**Comment by perry-mitchell** [comment]
Would happily accept a PR for `ref` usage.

**Comment by lbialy** [comment]
Isn't there one open?

**Comment by perry-mitchell** [comment]
@lbialy Indeed there is.. :sweat_smile:

**Comment by perry-mitchell** [comment]
Fixed by #19
